### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by Ir1d**
Test branch

### CODE REVIEW

**Comment by Ir1d** [comment]
Guess Travis was not as fast as I did.D

But anyway, we've known that branches are safe for different people adding different parts.

So, let's use branches.

@cjsoft

**Comment by cjsoft** [comment]
hao de ,
jiu yong fen zhi ba.

**Comment by cjsoft** [comment]
我们用小驼峰吧、

**Comment by Ir1d** [comment]
@cjsoft 随便吧。。。只要变量有意义就行。。。但是Google的代码规范里写的是明确禁止小驼峰？

不过cpplint能过。。。所以随意咯～

http://zh-google-styleguide.readthedocs.org/en/latest/google-cpp-styleguide/naming/

哦它主要是大驼峰。。。Pascal命名法233

**Pull request merged**
